import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.detara.store';

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/homepage',
          '/products',
          '/product/',
          '/custom-jewelry',
          '/kiss',
          '/about',
          '/contact',
          '/journal',
          '/journal/',
          '/diamond-guide',
          '/care-guide',
          '/ring-size-guide',
          '/shipping',
          '/refund',
          '/privacy',
          '/terms',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/login/',
          '/register/',
          '/checkout/',
          '/cart/',
          '/account/',
          '/wishlist/',
          '/order-confirmation/',
          '/auth/',
          '/kiss/product',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/homepage',
          '/products',
          '/product/',
          '/custom-jewelry',
          '/kiss',
          '/about',
          '/contact',
          '/journal',
          '/journal/',
          '/diamond-guide',
          '/care-guide',
          '/ring-size-guide',
          '/shipping',
          '/refund',
          '/privacy',
          '/terms',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/login/',
          '/register/',
          '/checkout/',
          '/cart/',
          '/account/',
          '/wishlist/',
          '/order-confirmation/',
          '/auth/',
          '/kiss/product',
        ],
      },
      {
        userAgent: 'GPTBot',
        allow: [
          '/',
          '/homepage',
          '/products',
          '/product/',
          '/custom-jewelry',
          '/kiss',
          '/about',
          '/contact',
          '/journal',
          '/journal/',
          '/diamond-guide',
          '/care-guide',
          '/ring-size-guide',
          '/shipping',
          '/refund',
          '/privacy',
          '/terms',
        ],
        disallow: ['/api/', '/_next/', '/admin/', '/checkout/', '/cart/', '/account/'],
      },
      {
        userAgent: 'PerplexityBot',
        allow: [
          '/',
          '/homepage',
          '/products',
          '/product/',
          '/custom-jewelry',
          '/kiss',
          '/about',
          '/contact',
          '/journal',
          '/journal/',
          '/diamond-guide',
          '/care-guide',
          '/ring-size-guide',
        ],
        disallow: ['/api/', '/_next/', '/admin/', '/checkout/', '/cart/', '/account/'],
      },
      {
        userAgent: 'ClaudeBot',
        allow: [
          '/',
          '/homepage',
          '/products',
          '/product/',
          '/custom-jewelry',
          '/kiss',
          '/about',
          '/contact',
          '/journal',
          '/journal/',
          '/diamond-guide',
          '/care-guide',
          '/ring-size-guide',
        ],
        disallow: ['/api/', '/_next/', '/admin/', '/checkout/', '/cart/', '/account/'],
      },
    ],
    sitemap: [`${baseUrl}/sitemap.xml`, `${baseUrl}/image-sitemap.xml`],
  };
}